; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:uno]
[env:uno_r4]
;platform = atmelavr
platform = renesas-ra
;board = uno
board = uno_r4_wifi
framework = arduino
lib_deps = coryjfowler/mcp_can@^1.5.1
monitor_speed = 115200
build_flags =
    -I src
    -I src/Asw
    -I src/Bsw/Adc
    -I src/Bsw/BswM
    -I src/Bsw/Can
    -I src/Bsw/CanIf
    -I src/Bsw/CanSM
    -I src/Bsw/CanTp
    -I src/Bsw/Com
    -I src/Bsw/ComM
    -I src/Bsw/Dcm
    -I src/Bsw/Dem
    -I src/Bsw/Det
    -I src/Bsw/Dio
    -I src/Bsw/E2E
    -I src/Bsw/E2EXf
    -I src/Bsw/E2EMon
    -I src/Bsw/EcuM
    -I src/Bsw/FiM
    -I src/Bsw/IoHwAb
    -I src/Bsw/Nm
    -I src/Bsw/NvM
    -I src/Bsw/PduR
    -I src/Bsw/Port
    -I src/Bsw/SchM
    -I src/Bsw/WdgM
    -I src/Hal
    -I src/Os
    -I src/Rte
